//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.ServiceReference2 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Student", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
    [System.SerializableAttribute()]
    public partial class Student : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OtherInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ScoreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OtherInfo {
            get {
                return this.OtherInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.OtherInfoField, value) != true)) {
                    this.OtherInfoField = value;
                    this.RaisePropertyChanged("OtherInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Score {
            get {
                return this.ScoreField;
            }
            set {
                if ((this.ScoreField.Equals(value) != true)) {
                    this.ScoreField = value;
                    this.RaisePropertyChanged("Score");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.IService2Unit8")]
    public interface IService2Unit8 {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IService2Unit8/Add")]
        void Add(Client.ServiceReference2.Student student);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IService2Unit8/Add")]
        System.Threading.Tasks.Task AddAsync(Client.ServiceReference2.Student student);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IService2Unit8/Remove")]
        void Remove(int n);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IService2Unit8/Remove")]
        System.Threading.Tasks.Task RemoveAsync(int n);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2Unit8/GetStudentsValue", ReplyAction="http://tempuri.org/IService2Unit8/GetStudentsValueResponse")]
        string GetStudentsValue();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2Unit8/GetStudentsValue", ReplyAction="http://tempuri.org/IService2Unit8/GetStudentsValueResponse")]
        System.Threading.Tasks.Task<string> GetStudentsValueAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService2Unit8Channel : Client.ServiceReference2.IService2Unit8, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service2Unit8Client : System.ServiceModel.ClientBase<Client.ServiceReference2.IService2Unit8>, Client.ServiceReference2.IService2Unit8 {
        
        public Service2Unit8Client() {
        }
        
        public Service2Unit8Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service2Unit8Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service2Unit8Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service2Unit8Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Add(Client.ServiceReference2.Student student) {
            base.Channel.Add(student);
        }
        
        public System.Threading.Tasks.Task AddAsync(Client.ServiceReference2.Student student) {
            return base.Channel.AddAsync(student);
        }
        
        public void Remove(int n) {
            base.Channel.Remove(n);
        }
        
        public System.Threading.Tasks.Task RemoveAsync(int n) {
            return base.Channel.RemoveAsync(n);
        }
        
        public string GetStudentsValue() {
            return base.Channel.GetStudentsValue();
        }
        
        public System.Threading.Tasks.Task<string> GetStudentsValueAsync() {
            return base.Channel.GetStudentsValueAsync();
        }
    }
}
