//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1Unit8")]
    public interface IService1Unit8 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1Unit8/Hello", ReplyAction="http://tempuri.org/IService1Unit8/HelloResponse")]
        string Hello(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1Unit8/Hello", ReplyAction="http://tempuri.org/IService1Unit8/HelloResponse")]
        System.Threading.Tasks.Task<string> HelloAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1Unit8/GetStudentsValue", ReplyAction="http://tempuri.org/IService1Unit8/GetStudentsValueResponse")]
        string GetStudentsValue();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1Unit8/GetStudentsValue", ReplyAction="http://tempuri.org/IService1Unit8/GetStudentsValueResponse")]
        System.Threading.Tasks.Task<string> GetStudentsValueAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Unit8Channel : Client.ServiceReference1.IService1Unit8, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Unit8Client : System.ServiceModel.ClientBase<Client.ServiceReference1.IService1Unit8>, Client.ServiceReference1.IService1Unit8 {
        
        public Service1Unit8Client() {
        }
        
        public Service1Unit8Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Unit8Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Unit8Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Unit8Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Hello(string name) {
            return base.Channel.Hello(name);
        }
        
        public System.Threading.Tasks.Task<string> HelloAsync(string name) {
            return base.Channel.HelloAsync(name);
        }
        
        public string GetStudentsValue() {
            return base.Channel.GetStudentsValue();
        }
        
        public System.Threading.Tasks.Task<string> GetStudentsValueAsync() {
            return base.Channel.GetStudentsValueAsync();
        }
    }
}
